version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Pré build phase - Exemplo baixar dependências se fosse necessario"
  build:
    commands:
      - echo "Testing and Building"
      - mvn clean test compile jar:jar
  post_build:
    commands:
      - echo "COMPILADO INDO PARA DEPLOY"
artifacts:
  files:
    - target/data-0.0.1-SNAPSHOT.jar