version: 0.2
phases:
  pre_build:
    commands:
      - echo "Pré build phase - Exemplo baixar dependências se fosse necessario"
  build:
    commands:
      - echo "Testing and Building"
      - mvn clean test compile jar:jar
  post_build:
    commands:
      - echo "Movendo os arquivos que serão feitos upload"
      - mv target/*.jar ./ROOT.jar
artifacts:
  files:
    - ROOT.jar