version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Pré build phase - Exemplo baixar dependências se fosse necessario"
  build:
    commands:
      - echo "Testing and Building"
      - mvn clean test
  post_build:
    commands:
      - echo "COMPILAR MVN PACKAGE"
      - mvn package
      - mv target/*.jar ./ROOT.jar
artifacts:
  files:
    - ROOT.war