version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Pré build phase - Exemplo baixar dependências se fosse necessario"
  build:
    commands:
      - echo "Testing and Building"
  post_build:
    commands:
      - echo "COMPILAR MVN INSTALL"
      - mvn install
artifacts:
  files:
    - target/data-0.0.1-SNAPSHOT.jar